# Generated by Django 2.2 on 2019-05-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0002_auto_20190507_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMachine', models.CharField(blank=True, max_length=300)),
                ('descriptionMachine', models.CharField(blank=True, max_length=500)),
                ('calibration', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('factory', models.CharField(max_length=130)),
                ('group', models.CharField(max_length=100)),
                ('subGroup', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('situation', models.CharField(blank=True, max_length=100)),
                ('manoFacture', models.CharField(blank=True, max_length=100)),
                ('identificationTag', models.CharField(blank=True, max_length=100)),
                ('serialNumber', models.CharField(max_length=100)),
                ('numberManofacturing', models.CharField(max_length=100)),
                ('numberInvoice', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('numberPatrimony', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('files', models.FileField(upload_to='image/%d%m%Y')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(upload_to='image/%Y/%m/%d/'),
        ),
    ]
