# Generated by Django 2.2 on 2019-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0005_auto_20190515_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
