# Generated by Django 2.2 on 2019-05-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0006_auto_20190515_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='registrationDate',
            field=models.DateField(auto_now=True),
        ),
    ]
