# Generated by Django 2.2 on 2019-05-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0007_machine_registrationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='files',
            field=models.FileField(upload_to='image/%Y/%m/%d/'),
        ),
    ]
