# Generated by Django 2.2 on 2019-05-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0008_auto_20190515_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='files',
            new_name='image',
        ),
    ]
