# Generated by Django 2.2 on 2019-05-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0010_auto_20190515_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.FileField(upload_to='image/%Y/%m/%d/'),
        ),
    ]
