# Generated by Django 2.2 on 2019-05-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0013_auto_20190515_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(max_length=900, upload_to='image/machine/%Y-%m-%d'),
        ),
    ]
