# Generated by Django 2.2 on 2019-05-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0014_auto_20190516_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='image',
        ),
    ]
