# Generated by Django 2.2 on 2019-05-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0015_remove_machine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.FileField(max_length=900, null=True, upload_to='image/machine/%Y-%m-%d'),
        ),
    ]
