# Generated by Django 2.2 on 2019-05-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0016_machine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.FileField(max_length=900, upload_to='image/machine/%Y-%m-%d'),
        ),
    ]
