# Generated by Django 2.2 on 2019-05-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0017_auto_20190516_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.FileField(upload_to='image/machine/%Y-%m-%d'),
        ),
    ]
