# Generated by Django 2.2 on 2019-05-16 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DNA', '0019_auto_20190516_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='image',
        ),
        migrations.CreateModel(
            name='bdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=900, upload_to='image/machine/%Y-%m-%d')),
                ('idmachine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DNA.Machine')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
