# Generated by Django 2.2 on 2019-05-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0020_auto_20190516_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='descriptionMachine',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nameMachine',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
