# Generated by Django 2.2 on 2019-05-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0021_auto_20190520_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='calibration',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nameMachine',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
