# Generated by Django 2.2 on 2019-05-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DNA', '0022_auto_20190520_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='calibration',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='machine',
            name='descriptionMachine',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
